services:
  app:
    build:
      context: .
      target: dev
    environment:
      - PORT=8080
      - HOST=0.0.0.0
      - OIDC_PROVIDER=http://localhost:7003
      - OIDC_CLIENT_ID=client-id
      - OIDC_CLIENT_SECRET=client-secret
      - OIDC_REDIRECT_URL=http://localhost:8080/api/oidc/callback
      - DATABASE_URL=postgres://durn:durn@db:5432/durn
      - DOMAIN=localhost
    ports: [ 8080:8080 ]
    command: sh -c /app/run.sh
    depends_on:
      db:
        condition: service_healthy
    develop:
      watch:
        - path: .
          action: rebuild
    configs:
      - source: nginx.conf
        target: /etc/nginx/nginx.conf
  db:
    image: 'postgres:latest'
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: durn
      POSTGRES_PASSWORD: durn
      POSTGRES_DB: durn
    healthcheck:
      test:
        - "CMD-SHELL"
        - "sh -c 'pg_isready -d durn -U durn'"
      interval: 1s
      timeout: 5s
      retries: 5
      start_period: 5s
  nyckeln:
    image: ghcr.io/datasektionen/nyckeln-under-dorrmattan
    ports:
      - 7002:7002
      - 7003:7003
      - 7004:7004
    configs:
      - source: nyckeln.yaml
        target: /config.yaml

configs:
  nginx.conf:
    content: | 
      events {}

      http {
        server {
          listen 7003;

          location / {
            proxy_pass http://nyckeln:7003;
          }
        }
      }

  nyckeln.yaml:
    content: |
      clients:
        - id: client-id
          secret: client-secret
          redirect_uris:
            - http://localhost:8080/api/oidc/callback

      users:
        - ug_kth_id: some-id
          kth_id: turetek
          email: turetek@kth.se
          first_name: Ture
          family_name: Teknolog
          hive_tags:
            - id: personal_email
              content: turetek@gmail.com

      hive:
        groups:
          - name: Valberedningens ordförande
            id: valberedning-ordf
            domain: example.com
            members:
              - turetek
            permissions:
              - id: admin-read
              - id: admin-write

